-- Generated from this Noita installation's data.wak.
-- Contains spawnable player items and collectible item entities; internal base/test XML is excluded.
return {
    { path = "data/entities/items/pickup/bloodmoney_10.xml", name = "$item_bloodmoney_10", description = "Lorem ipsum", icon = "data/ui_gfx/items/book.png", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/bloodmoney_1000.xml", name = "$item_bloodmoney_1000", description = "Lorem ipsum", icon = "data/ui_gfx/items/goldnugget.png", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/bloodmoney_10000.xml", name = "$item_bloodmoney_10000", description = "Lorem ipsum", icon = "data/ui_gfx/items/goldnugget.png", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/bloodmoney_200.xml", name = "$item_bloodmoney_200", description = "Lorem ipsum", icon = "data/ui_gfx/items/goldnugget.png", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/bloodmoney_200000.xml", name = "$item_bloodmoney_200000", description = "Lorem ipsum", icon = "data/ui_gfx/items/goldnugget.png", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/bloodmoney_50.xml", name = "$item_bloodmoney_50", description = "Lorem ipsum", icon = "data/ui_gfx/items/goldnugget.png", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/bloodmoney_x.xml", name = "$reward_gold_statue", description = "Lorem ipsum", icon = "data/ui_gfx/items/goldnugget.png", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/chest_random_super.xml", name = "$item_chest_treasure", description = "", icon = "data/ui_gfx/inventory/inventory_box.png", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/chest_random.xml", name = "$item_chest_treasure", description = "", icon = "data/ui_gfx/inventory/inventory_box.png", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/goldnugget_10.xml", name = "$item_goldnugget_10", description = "Lorem ipsum", icon = "data/ui_gfx/items/book.png", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/goldnugget_1000.xml", name = "$item_goldnugget_1000", description = "Lorem ipsum", icon = "data/ui_gfx/items/goldnugget.png", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/goldnugget_10000.xml", name = "$item_goldnugget_10000", description = "Lorem ipsum", icon = "data/ui_gfx/items/goldnugget.png", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/goldnugget_200.xml", name = "$item_goldnugget_200", description = "Lorem ipsum", icon = "data/ui_gfx/items/goldnugget.png", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/goldnugget_200000.xml", name = "$item_goldnugget_200000", description = "Lorem ipsum", icon = "data/ui_gfx/items/goldnugget.png", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/goldnugget_50.xml", name = "$item_goldnugget_50", description = "Lorem ipsum", icon = "data/ui_gfx/items/goldnugget.png", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/goldnugget_x.xml", name = "$reward_gold_statue", description = "Lorem ipsum", icon = "data/ui_gfx/items/goldnugget.png", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/goldnugget.xml", name = "$item_goldnugget_10", description = "Lorem ipsum", icon = "data/ui_gfx/items/goldnugget.png", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/heart_better.xml", name = "$item_heart_better", description = "", icon = "data/items_gfx/heart_extrahp.xml", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/heart_evil.xml", name = "$item_heart", description = "", icon = "data/items_gfx/heart_extrahp_evil.xml", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/heart_fullhp_temple.xml", name = "$item_heart_fullhp", description = "", icon = "data/items_gfx/heart.xml", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/heart_fullhp.xml", name = "$item_heart_fullhp", description = "", icon = "data/items_gfx/heart.xml", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/heart.xml", name = "$item_heart", description = "", icon = "data/items_gfx/heart_extrahp.xml", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/perk_reroll.xml", name = "$item_perk_reroll", description = "", icon = "data/buildings_gfx/perk_reroll.png", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/spell_refresh.xml", name = "$item_spell_refresh", description = "", icon = "data/items_gfx/spell_refresh.xml", category = "BONUSES", advanced = false },
    { path = "data/entities/items/pickup/utility_box.xml", name = "$item_utility_box", description = "", icon = "data/ui_gfx/inventory/inventory_box.png", category = "BONUSES", advanced = false },
    { path = "data/entities/items/books/book_00.xml", name = "$booktitle00", description = "$bookdesc00", icon = "data/ui_gfx/items/emerald_tablet.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_01.xml", name = "$booktitle01", description = "$bookdesc01", icon = "data/ui_gfx/items/emerald_tablet.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_02.xml", name = "$booktitle02", description = "$bookdesc02", icon = "data/ui_gfx/items/emerald_tablet.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_03.xml", name = "$booktitle03", description = "$bookdesc03", icon = "data/ui_gfx/items/emerald_tablet.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_04.xml", name = "$booktitle04", description = "$bookdesc04", icon = "data/ui_gfx/items/emerald_tablet.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_05.xml", name = "$booktitle05", description = "$bookdesc05", icon = "data/ui_gfx/items/emerald_tablet.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_06.xml", name = "$booktitle06", description = "$bookdesc06", icon = "data/ui_gfx/items/emerald_tablet.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_07.xml", name = "$booktitle07", description = "$bookdesc07", icon = "data/ui_gfx/items/emerald_tablet.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_08.xml", name = "$booktitle08", description = "$bookdesc08", icon = "data/ui_gfx/items/emerald_tablet.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_09.xml", name = "$booktitle09", description = "$bookdesc09", icon = "data/ui_gfx/items/emerald_tablet.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_10.xml", name = "$booktitle10", description = "$bookdesc10", icon = "data/ui_gfx/items/emerald_tablet.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_all_spells.xml", name = "$booktitle_allspells", description = "$bookdesc_allspells", icon = "data/ui_gfx/items/laboratory_tablet.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_barren.xml", name = "$booktitle_barren", description = "$bookdesc_barren", icon = "data/items_gfx/book.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_bunker.xml", name = "$booktitle_fisher", description = "$bookdesc_fisher", icon = "data/items_gfx/book.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_corpse.xml", name = "$booktitle_corpse", description = "$bookdesc_corpse", icon = "data/ui_gfx/items/emerald_tablet.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_diamond.xml", name = "$item_book_diamond", description = "$itemdesc_book_diamond", icon = "data/items_gfx/book.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_essences.xml", name = "$item_book_essences", description = "$itemdesc_book_essences", icon = "data/items_gfx/book.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_hint.xml", name = "$item_book_hint", description = "$itemdesc_book_hint", icon = "data/items_gfx/book.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_mestari.xml", name = "$booktitle_mestari", description = "$bookdesc_mestari", icon = "data/items_gfx/book.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_moon.xml", name = "$item_book_moon", description = "$itemdesc_book_moon", icon = "data/items_gfx/book.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_music_a.xml", name = "$item_book_music", description = "$itemdesc_book_music", icon = "data/items_gfx/book.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_music_b.xml", name = "$item_book_music_b", description = "$itemdesc_book_music_b", icon = "data/items_gfx/book.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_music_c.xml", name = "$item_book_music_c", description = "$itemdesc_book_music_c", icon = "data/items_gfx/book.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_robot.xml", name = "$item_book_robot", description = "$itemdesc_book_robot", icon = "data/items_gfx/book.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_s_a.xml", name = "$item_book_s_a", description = "$itemdesc_book_s_a", icon = "data/items_gfx/book_s.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_s_b.xml", name = "$item_book_s_a", description = "$itemdesc_book_s_b", icon = "data/items_gfx/book_s.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_s_c.xml", name = "$item_book_s_a", description = "$itemdesc_book_s_c", icon = "data/items_gfx/book_s.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_s_d.xml", name = "$item_book_s_a", description = "$itemdesc_book_s_d", icon = "data/items_gfx/book_s.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_s_e.xml", name = "$item_book_s_a", description = "$itemdesc_book_s_e", icon = "data/items_gfx/book_s.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/books/book_tree.xml", name = "$booktitle_tree", description = "$bookdesc_tree", icon = "data/ui_gfx/items/emerald_tablet.png", category = "BOOKS", advanced = false },
    { path = "data/entities/items/pickup/jar_of_urine.xml", name = "$item_jar", description = "$item_description_jar", icon = "data/ui_gfx/items/jar.png", category = "CONTAINERS", advanced = false },
    { path = "data/entities/items/pickup/jar.xml", name = "$item_jar", description = "$item_description_jar", icon = "data/ui_gfx/items/jar.png", category = "CONTAINERS", advanced = false },
    { path = "data/entities/items/pickup/potion_aggressive.xml", name = "$item_potion", description = "$item_description_potion", icon = "data/ui_gfx/items/potion_alchemist.png", category = "CONTAINERS", advanced = false },
    { path = "data/entities/items/pickup/potion_alcohol.xml", name = "$item_potion", description = "$item_description_potion", icon = "data/ui_gfx/items/potion.png", category = "CONTAINERS", advanced = false },
    { path = "data/entities/items/pickup/potion_beer.xml", name = "$item_potion", description = "$item_description_potion", icon = "data/ui_gfx/items/potion.png", category = "CONTAINERS", advanced = false },
    { path = "data/entities/items/pickup/potion_empty.xml", name = "$item_potion", description = "$item_description_potion", icon = "data/ui_gfx/items/potion.png", category = "CONTAINERS", advanced = false },
    { path = "data/entities/items/pickup/potion_milk.xml", name = "$item_potion", description = "$item_description_potion", icon = "data/ui_gfx/items/potion.png", category = "CONTAINERS", advanced = false },
    { path = "data/entities/items/pickup/potion_mimic.xml", name = "$item_potion_mimic", description = "", icon = "data/ui_gfx/inventory/inventory_box.png", category = "CONTAINERS", advanced = false },
    { path = "data/entities/items/pickup/potion_porridge.xml", name = "$item_potion", description = "$item_description_potion", icon = "data/ui_gfx/items/potion.png", category = "CONTAINERS", advanced = false },
    { path = "data/entities/items/pickup/potion_random_material.xml", name = "$item_potion", description = "$item_description_potion", icon = "data/ui_gfx/items/potion.png", category = "CONTAINERS", advanced = false },
    { path = "data/entities/items/pickup/potion_secret.xml", name = "$item_potion", description = "$item_description_potion", icon = "data/ui_gfx/items/potion.png", category = "CONTAINERS", advanced = false },
    { path = "data/entities/items/pickup/potion_slime.xml", name = "$item_potion", description = "$item_description_potion", icon = "data/ui_gfx/items/potion.png", category = "CONTAINERS", advanced = false },
    { path = "data/entities/items/pickup/potion_starting.xml", name = "$item_potion", description = "$item_description_potion", icon = "data/ui_gfx/items/potion.png", category = "CONTAINERS", advanced = false },
    { path = "data/entities/items/pickup/potion_vomit.xml", name = "$item_potion", description = "$item_description_potion", icon = "data/ui_gfx/items/potion.png", category = "CONTAINERS", advanced = false },
    { path = "data/entities/items/pickup/potion_water.xml", name = "$item_potion", description = "$item_description_potion", icon = "data/ui_gfx/items/potion.png", category = "CONTAINERS", advanced = false },
    { path = "data/entities/items/pickup/potion.xml", name = "$item_potion", description = "$item_description_potion", icon = "data/ui_gfx/items/potion.png", category = "CONTAINERS", advanced = false },
    { path = "data/entities/items/pickup/powder_stash.xml", name = "$item_powder_stash_3", description = "$itemdesc_powder_stash_3", icon = "data/ui_gfx/items/material_pouch.png", category = "CONTAINERS", advanced = false },
    { path = "data/entities/items/pickup/egg_fire.xml", name = "$item_egg_fire", description = "$item_description_egg_fire", icon = "data/ui_gfx/items/egg_red.png", category = "EGGS", advanced = false },
    { path = "data/entities/items/pickup/egg_hollow.xml", name = "$item_egg_hollow", description = "$itemdesc_egg_hollow", icon = "data/ui_gfx/items/egg_slime.png", category = "EGGS", advanced = false },
    { path = "data/entities/items/pickup/egg_monster.xml", name = "$item_egg", description = "$item_description_egg", icon = "data/ui_gfx/items/egg.png", category = "EGGS", advanced = false },
    { path = "data/entities/items/pickup/egg_purple.xml", name = "$item_egg_purple", description = "$item_description_egg_purple", icon = "data/ui_gfx/items/egg_purple.png", category = "EGGS", advanced = false },
    { path = "data/entities/items/pickup/egg_red.xml", name = "$item_egg", description = "$item_description_egg", icon = "data/ui_gfx/items/egg_red.png", category = "EGGS", advanced = false },
    { path = "data/entities/items/pickup/egg_slime.xml", name = "$item_egg_slime", description = "$item_description_egg_slime", icon = "data/ui_gfx/items/egg_slime.png", category = "EGGS", advanced = false },
    { path = "data/entities/items/pickup/egg_spiders.xml", name = "$item_egg_purple", description = "$item_description_egg_purple", icon = "data/ui_gfx/items/egg_purple.png", category = "EGGS", advanced = false },
    { path = "data/entities/items/pickup/egg_worm.xml", name = "$item_egg_worm", description = "$item_description_egg_worm", icon = "data/ui_gfx/items/egg_worm.png", category = "EGGS", advanced = false },
    { path = "data/entities/items/orbs/orb_00.xml", name = "$item_orb", description = "", icon = "data/items_gfx/orbs/orb_00.xml", category = "ORBS", advanced = false },
    { path = "data/entities/items/orbs/orb_01.xml", name = "$item_orb", description = "", icon = "data/items_gfx/orbs/orb_01.xml", category = "ORBS", advanced = false },
    { path = "data/entities/items/orbs/orb_02.xml", name = "$item_orb", description = "", icon = "data/items_gfx/orbs/orb_02.xml", category = "ORBS", advanced = false },
    { path = "data/entities/items/orbs/orb_03.xml", name = "$item_orb", description = "", icon = "data/items_gfx/orbs/orb_03.xml", category = "ORBS", advanced = false },
    { path = "data/entities/items/orbs/orb_04.xml", name = "$item_orb", description = "", icon = "data/items_gfx/orbs/orb_04.xml", category = "ORBS", advanced = false },
    { path = "data/entities/items/orbs/orb_05.xml", name = "$item_orb", description = "", icon = "data/items_gfx/orbs/orb_05.xml", category = "ORBS", advanced = false },
    { path = "data/entities/items/orbs/orb_06.xml", name = "$item_orb", description = "", icon = "data/items_gfx/orbs/orb_06.xml", category = "ORBS", advanced = false },
    { path = "data/entities/items/orbs/orb_07.xml", name = "$item_orb", description = "", icon = "data/items_gfx/orbs/orb_07.xml", category = "ORBS", advanced = false },
    { path = "data/entities/items/orbs/orb_08.xml", name = "$item_orb", description = "", icon = "data/items_gfx/orbs/orb_08.xml", category = "ORBS", advanced = false },
    { path = "data/entities/items/orbs/orb_09.xml", name = "$item_orb", description = "", icon = "data/items_gfx/orbs/orb_09.xml", category = "ORBS", advanced = false },
    { path = "data/entities/items/orbs/orb_10.xml", name = "$item_orb", description = "", icon = "data/items_gfx/orbs/orb_10.xml", category = "ORBS", advanced = false },
    { path = "data/entities/items/orbs/orb_11.xml", name = "$item_orb", description = "", icon = "data/items_gfx/orbs/orb_11.xml", category = "ORBS", advanced = false },
    { path = "data/entities/items/orbs/orb_13.xml", name = "$item_orb", description = "", icon = "data/items_gfx/orbs/orb.xml", category = "ORBS", advanced = false },
    { path = "data/entities/items/easter/beer_bottle.xml", name = "$item_potion", description = "$item_description_potion", icon = "data/items_gfx/beer_bottle.png", category = "OTHER", advanced = true },
    { path = "data/entities/items/easter/minit_watering.xml", name = "Potion", description = "Equip and throw.", icon = "data/items_gfx/minit_watering_can.png", category = "OTHER", advanced = true },
    { path = "data/entities/items/pickup/cape.xml", name = "Fire protection cape", description = "", icon = "data/items_gfx/cape/default.xml", category = "OTHER", advanced = false },
    { path = "data/entities/items/pickup/physics_die.xml", name = "$item_die", description = "$itemdesc_die", icon = "data/ui_gfx/items/die.png", category = "OTHER", advanced = false },
    { path = "data/entities/items/pickup/physics_gold_orb_greed.xml", name = "$item_gold_orb_greed", description = "$itemdesc_gold_orb_greed", icon = "data/ui_gfx/items/orb_gold_greed.png", category = "OTHER", advanced = false },
    { path = "data/entities/items/pickup/physics_gold_orb.xml", name = "$item_gold_orb", description = "$itemdesc_gold_orb", icon = "data/ui_gfx/items/orb_gold.png", category = "OTHER", advanced = false },
    { path = "data/entities/items/pickup/physics_greed_die.xml", name = "$item_greed_die", description = "$itemdesc_greed_die", icon = "data/ui_gfx/items/greed_die.png", category = "OTHER", advanced = false },
    { path = "data/entities/items/shop_cape.xml", name = "Fire protection cape", description = "", icon = "data/fonts/font_pixel_white.xml", category = "OTHER", advanced = true },
    { path = "data/entities/items/shop_potion.xml", name = "$item_potion", description = "$item_description_potion", icon = "data/ui_gfx/items/potion.png", category = "OTHER", advanced = true },
    { path = "data/entities/items/pickup/broken_wand.xml", name = "$item_broken_wand", description = "$item_description_broken_wand", icon = "data/ui_gfx/items/broken_wand.png", category = "QUEST", advanced = false },
    { path = "data/entities/items/pickup/essence_air.xml", name = "$item_essence_air", description = "$itemdesc_essence_air", icon = "data/items_gfx/essences/essence_air.png", category = "QUEST", advanced = false },
    { path = "data/entities/items/pickup/essence_alcohol.xml", name = "$item_essence_alcohol", description = "$itemdesc_essence_alcohol", icon = "data/items_gfx/essences/essence_alcohol.png", category = "QUEST", advanced = false },
    { path = "data/entities/items/pickup/essence_fire.xml", name = "$item_essence_fire", description = "$itemdesc_essence_fire", icon = "data/items_gfx/essences/essence_fire.png", category = "QUEST", advanced = false },
    { path = "data/entities/items/pickup/essence_laser.xml", name = "$item_essence_laser", description = "$itemdesc_essence_laser", icon = "data/items_gfx/essences/essence_laser.png", category = "QUEST", advanced = false },
    { path = "data/entities/items/pickup/essence_water.xml", name = "$item_essence_water", description = "$itemdesc_essence_water", icon = "data/items_gfx/essences/essence_water.png", category = "QUEST", advanced = false },
    { path = "data/entities/items/pickup/gourd.xml", name = "$item_gourd", description = "$itemdesc_gourd", icon = "data/ui_gfx/items/gourd.png", category = "QUEST", advanced = false },
    { path = "data/entities/items/pickup/greed_curse.xml", name = "$item_essence_greed", description = "$itemdesc_essence_greed", icon = "data/items_gfx/greed_curse.png", category = "QUEST", advanced = false },
    { path = "data/entities/items/pickup/safe_haven.xml", name = "$item_safe_haven", description = "$item_description_safe_haven", icon = "data/ui_gfx/items/safe_haven.png", category = "QUEST", advanced = false },
    { path = "data/entities/items/pickup/summon_portal_broken.xml", name = "$action_broken_spell", description = "$actiondesc_broken_spell", icon = "data/items_gfx/broken_spell.png", category = "QUEST", advanced = false },
    { path = "data/entities/items/pickup/sun/sunseed.xml", name = "$item_sunseed", description = "$itemdesc_sunseed", icon = "data/ui_gfx/items/sunseed.png", category = "QUEST", advanced = false },
    { path = "data/entities/items/pickup/beamstone.xml", name = "$item_mega_beam_stone", description = "$itemdesc_mega_beam_stone", icon = "data/ui_gfx/items/beamstone.png", category = "STONES", advanced = false },
    { path = "data/entities/items/pickup/brimstone.xml", name = "$item_brimstone", description = "$item_description_brimstone", icon = "data/ui_gfx/items/brimstone.png", category = "STONES", advanced = false },
    { path = "data/entities/items/pickup/evil_eye.xml", name = "$item_evil_eye", description = "$item_description_evil_eye", icon = "data/ui_gfx/items/evil_eye.png", category = "STONES", advanced = false },
    { path = "data/entities/items/pickup/moon.xml", name = "$item_moon", description = "$item_description_moon", icon = "data/ui_gfx/items/moon.png", category = "STONES", advanced = false },
    { path = "data/entities/items/pickup/musicstone.xml", name = "$item_musicstone", description = "$itemdesc_musicstone", icon = "data/ui_gfx/items/musicstone.png", category = "STONES", advanced = false },
    { path = "data/entities/items/pickup/poopstone.xml", name = "$item_kakka", description = "$itemdesc_kakka", icon = "data/ui_gfx/items/kakke.png", category = "STONES", advanced = false },
    { path = "data/entities/items/pickup/runestones/runestone_base.xml", name = "$item_runestone_slow", description = "$itemdesc_runestone", icon = "data/ui_gfx/items/runestone_slow.png", category = "STONES", advanced = false },
    { path = "data/entities/items/pickup/runestones/runestone_disc.xml", name = "$item_runestone_disc", description = "$itemdesc_runestone", icon = "data/ui_gfx/items/runestone_disc.png", category = "STONES", advanced = false },
    { path = "data/entities/items/pickup/runestones/runestone_fireball.xml", name = "$item_runestone_fireball", description = "$itemdesc_runestone", icon = "data/ui_gfx/items/runestone_fireball.png", category = "STONES", advanced = false },
    { path = "data/entities/items/pickup/runestones/runestone_laser.xml", name = "$item_runestone_laser", description = "$itemdesc_runestone", icon = "data/ui_gfx/items/runestone_laser.png", category = "STONES", advanced = false },
    { path = "data/entities/items/pickup/runestones/runestone_lava.xml", name = "$item_runestone_lava", description = "$itemdesc_runestone", icon = "data/ui_gfx/items/runestone_lava.png", category = "STONES", advanced = false },
    { path = "data/entities/items/pickup/runestones/runestone_metal.xml", name = "$item_runestone_metal", description = "$itemdesc_runestone", icon = "data/ui_gfx/items/runestone_metal.png", category = "STONES", advanced = false },
    { path = "data/entities/items/pickup/runestones/runestone_null.xml", name = "$item_runestone_null", description = "$itemdesc_runestone", icon = "data/ui_gfx/items/runestone_null.png", category = "STONES", advanced = false },
    { path = "data/entities/items/pickup/runestones/runestone_slow.xml", name = "$item_runestone_slow", description = "$itemdesc_runestone", icon = "data/ui_gfx/items/runestone_slow.png", category = "STONES", advanced = false },
    { path = "data/entities/items/pickup/stonestone.xml", name = "$item_stonestone", description = "$itemdesc_stonestone", icon = "data/ui_gfx/items/stonestone.png", category = "STONES", advanced = false },
    { path = "data/entities/items/pickup/sun/sunstone.xml", name = "$item_seed_c", description = "$itemdesc_seed_c", icon = "data/ui_gfx/items/sunseed_2.png", category = "STONES", advanced = false },
    { path = "data/entities/items/pickup/thunderstone.xml", name = "$item_thunderstone", description = "$item_description_thunderstone", icon = "data/ui_gfx/items/ingredient_1.png", category = "STONES", advanced = false },
    { path = "data/entities/items/pickup/wandstone.xml", name = "$item_wandstone", description = "$itemdesc_wandstone", icon = "data/ui_gfx/items/wandstone.png", category = "STONES", advanced = false },
    { path = "data/entities/items/pickup/waterstone.xml", name = "$item_waterstone", description = "$item_description_waterstone", icon = "data/ui_gfx/items/waterstone.png", category = "STONES", advanced = false },
    { path = "data/entities/items/flute.xml", name = "$item_ocarina", description = "", icon = "data/items_gfx/flute.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/kantele.xml", name = "$item_kantele", description = "", icon = "data/items_gfx/kantele.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/leukaluu_kantele.xml", name = "$item_leukaluu_kantele", description = "", icon = "data/items_gfx/wands/custom/leukaluu_kantele.png", category = "WANDS", advanced = false },
    { path = "data/entities/items/shop_wand_level_01.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = true },
    { path = "data/entities/items/starting_bomb_wand_rng_daily.xml", name = "bomb_wand", description = "", icon = "data/items_gfx/bomb_wand.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/starting_bomb_wand_rng.xml", name = "bomb_wand", description = "", icon = "data/items_gfx/bomb_wand.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/starting_bomb_wand.xml", name = "bomb_wand", description = "", icon = "data/items_gfx/bomb_wand.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/starting_wand_rng_daily.xml", name = "default_gun", description = "", icon = "data/items_gfx/handgun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/starting_wand_rng.xml", name = "default_gun", description = "", icon = "data/items_gfx/handgun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/starting_wand.xml", name = "default_gun", description = "", icon = "data/items_gfx/handgun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_arpaluu.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_daily_01.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_daily_02.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_daily_03.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_daily_04.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_daily_05.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_daily_06.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_kiekurakeppi.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_leukaluu.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_level_01_better.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_level_01_p.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_level_01.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_level_02_better.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_level_02_p.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_level_02.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_level_03_better.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_level_03_p.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_level_03.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_level_04_better.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_level_04_p.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_level_04.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_level_05_better.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_level_05_p.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_level_05.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_level_06_better.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_level_06_p.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_level_06.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_level_10.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_petri.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_ruusu.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_unshuffle_01_p.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_unshuffle_01.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_unshuffle_02_p.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_unshuffle_02.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_unshuffle_03_p.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_unshuffle_03.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_unshuffle_04_p.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_unshuffle_04.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_unshuffle_05_p.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_unshuffle_05.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_unshuffle_06_p.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_unshuffle_06.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_unshuffle_10.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_valtikka.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_varpuluuta.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_vasta.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wand_vihta.xml", name = "Rapid bolt wand", description = "", icon = "data/items_gfx/machinegun.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/custom/digger_01.xml", name = "fire_wand", description = "", icon = "data/items_gfx/wands/custom/scepter_01.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/experimental/experimental_wand_1.xml", name = "experimental_wand_1", description = "", icon = "data/entities/items/wands/experimental/experimental_wand_1_sprite.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/experimental/experimental_wand_2.xml", name = "experimental_wand_2", description = "", icon = "data/entities/items/wands/experimental/experimental_wand_2_sprite.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/experimental/experimental_wand_3.xml", name = "experimental_wand_3", description = "", icon = "data/items_gfx/wands/custom/actual_wand.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/experimental/experimental_wand_4.xml", name = "$item_chainsaw", description = "", icon = "data/items_gfx/wands/custom/chainsaw.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/level_01/wand_001.xml", name = "Good Rapid bolt wand", description = "", icon = "data/items_gfx/wands/wand_0484.png", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/level_01/wand_002.xml", name = "Good Rapid bolt wand", description = "", icon = "data/items_gfx/wands/wand_0654.png", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/level_01/wand_003.xml", name = "Neutral Rapid bolt wand", description = "", icon = "data/items_gfx/wands/wand_0958.png", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/level_01/wand_004.xml", name = "Antique Rapid bolt wand", description = "", icon = "data/items_gfx/wands/wand_0516.png", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/level_01/wand_005.xml", name = "Slim Rapid bolt wand", description = "", icon = "data/items_gfx/wands/wand_0484.png", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/level_01/wand_006.xml", name = "Superior Rapid bolt wand", description = "", icon = "data/items_gfx/wands/wand_0058.png", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/level_01/wand_007.xml", name = "Shiny Rapid bolt wand", description = "", icon = "data/items_gfx/wands/wand_0120.png", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/level_01/wand_008.xml", name = "Solid Rapid bolt wand", description = "", icon = "data/items_gfx/wands/wand_0898.png", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/level_01/wand_009.xml", name = "Turbo Rapid bolt wand", description = "", icon = "data/items_gfx/wands/wand_0724.png", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/level_01/wand_010.xml", name = "Large Rapid bolt wand", description = "", icon = "data/items_gfx/wands/wand_0326.png", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/level_01/wand_011.xml", name = "Vanilla Rapid bolt wand", description = "", icon = "data/items_gfx/wands/wand_0374.png", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/level_01/wand_012.xml", name = "Bad Rapid bolt wand", description = "", icon = "data/items_gfx/wands/wand_0324.png", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/level_01/wand_013.xml", name = "Large Rapid bolt wand", description = "", icon = "data/items_gfx/wands/wand_0309.png", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/level_01/wand_014.xml", name = "Slick Rapid bolt wand", description = "", icon = "data/items_gfx/wands/wand_0230.png", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/level_01/wand_015.xml", name = "Bulky Rapid bolt wand", description = "", icon = "data/items_gfx/wands/wand_0063.png", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/level_01/wand_016.xml", name = "Giga Rapid bolt wand", description = "", icon = "data/items_gfx/wands/wand_0830.png", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/level_01/wand_017.xml", name = "Type a Rapid bolt wand", description = "", icon = "data/items_gfx/wands/wand_1000.png", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/wand_good/wand_good_1.xml", name = "wand_good_1", description = "", icon = "data/items_gfx/wands/custom/good_01.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/wand_good/wand_good_2.xml", name = "wand_good_2", description = "", icon = "data/items_gfx/wands/custom/good_02.xml", category = "WANDS", advanced = false },
    { path = "data/entities/items/wands/wand_good/wand_good_3.xml", name = "wand_good_3", description = "", icon = "data/items_gfx/wands/custom/good_03.xml", category = "WANDS", advanced = false },
}
