#!/usr/bin/env python3
"""Reject development-process residue from production-facing source files."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

SKIP_PREFIXES = (
    "tests/",
    "files/qa/",
    "files/diagnostics/",
)

TEXT_SUFFIXES = {".lua", ".py", ".md", ".txt", ".xml", ".yml", ".yaml"}

RULES = (
    ("numbered internal test chronology", re.compile(r"\bTEST\s+\d+\b")),
    ("test-only production export", re.compile(r"\b[A-Za-z0-9_]+_for_test\b")),
    ("conversation-specific wording", re.compile(r"\b(?:the\s+)?user['’]s\s+build\b", re.IGNORECASE)),
    ("conversation-specific wording", re.compile(r"\bat\s+the\s+user['’]s\s+request\b", re.IGNORECASE)),
    ("internal numbered runtime log label", re.compile(r"\[MCM\s*(?:TEST\s*)?\d{2,}\]", re.IGNORECASE)),
    ("AI tool/model attribution residue", re.compile(
        r"\b(?:ChatGPT|OpenAI|Claude|Gemini|Copilot|LLM|AI[- ]generated|generated by AI)\b",
        re.IGNORECASE,
    )),
)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", nargs="?", type=Path, default=Path("metamorph_creative_menu"))
    args = parser.parse_args()
    root = args.root.resolve()

    failures: list[str] = []
    checked = 0
    for path in sorted(root.rglob("*")):
        if not path.is_file() or path.suffix.lower() not in TEXT_SUFFIXES:
            continue
        relative = path.relative_to(root).as_posix()
        if any(relative.startswith(prefix) for prefix in SKIP_PREFIXES):
            continue
        checked += 1
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for line_number, line in enumerate(text.splitlines(), 1):
            for label, pattern in RULES:
                if pattern.search(line):
                    failures.append(f"{relative}:{line_number}: {label}: {line.strip()[:180]}")

    if failures:
        print("SOURCE_HYGIENE=FAIL")
        for failure in failures:
            print(failure)
        return 1

    print(f"SOURCE_HYGIENE=PASS files={checked}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
