local root=assert(arg[1],"root required")
local text=assert(io.open(root.."/init.lua","rb")):read("*a")
assert(not string.find(text,"dev_mode.lua",1,true),"Workshop init still loads dev_mode.lua")
assert(not string.find(text,"files/diagnostics/service.lua",1,true),"Workshop init still loads diagnostics service")
assert(not string.find(text,"files/qa/controller.lua",1,true),"Workshop init still loads QA controller")
assert(not string.find(text,"METAMORPH_CREATIVE_MENU_DEV_MODE",1,true),"Workshop init still exposes dev-mode global")
io.write("workshop_runtime_composition=PASS dev_mode_unloaded=true qa_unloaded=true diagnostics_unloaded=true\n")
