local root=assert(arg[1],"root required")
local text=assert(io.open(root.."/files/integrations/ew/bootstrap.lua","rb")):read("*a")
assert(not string.find(text,"dev_mode.lua",1,true),"EW bootstrap still loads dev_mode.lua")
assert(not string.find(text,"bridge/qa.lua",1,true),"EW bootstrap still loads full QA bridge")
assert(not string.find(text,"bridge/qa_reserved.lua",1,true),"EW bootstrap still loads QA placeholder module")
assert(string.find(text,"function rpc.reserved_protocol_slot_3",1,true),"EW bootstrap no longer preserves reserved RPC slot 3")
io.write("workshop_ew_composition=PASS qa_unloaded=true reserved_slot_3=true\n")
