local root=assert(arg[1],"root required")
local mathx=assert(dofile(root.."/files/features/forms/scripted_attack_math.lua"))
local function near(a,b) return math.abs(a-b)<0.00001 end
local dragon=mathx.radial(10,100,0,false)
assert(#dragon==10 and near(dragon[1].x,100) and near(dragon[1].y,0),"boss dragon radial geometry changed")
local limbs=mathx.radial_degrees(8,230,0)
assert(#limbs==8 and near(limbs[1].x,230) and near(limbs[3].y,230),"boss limbs 8-way geometry changed")
local fish=mathx.radial(8,80,math.pi*0.25,true)
assert(#fish==8 and fish[1].y<0,"fish giga y-axis convention changed")
local fire=mathx.firepillar(10)
assert(#fire==10 and fire[1].y<0 and fire[#fire].y<0,"centipede firepillar fan changed")
local vx,vy=mathx.aimed(0,0,3,4,20)
assert(near(vx,12) and near(vy,16),"aimed normalization changed")
print("form_scripted_attack_math=PASS dragon10=true limbs8=true fish8=true firepillar=true aimed=true")
